Refactor: Remove unnecessary if statement
- Remove if statement that is always true if reached
- Revise comments

diff --git a/config_shell b/config_shell
--- a/config_shell
+++ b/config_shell
@@ -11,25 +11,24 @@ fi
 if ! grep -q "^${zsh_path}$" /etc/shells; then
   printf "${zsh_path}\n" >> /etc/shells
 
-  # Exit if we can't create the directory
+  # Exit if we can't add the shell path
   if [[ $? -ne 0 ]]; then
     printf 'entry for zsh not added to /etc/shell' >&2
     exit 128
   fi
 fi
 
-# Create $HOME/.config/zsh if necessary
+# Make sure the zsh config directory exists
 mkdir -p "$HOME/.config/zsh"
 
-# Exit if we can't create the directory
-if [[ $? -ne 0 ]]; then
-  printf "$HOME/.config/zsh not created" >&2
+# Exit if the zsh config directory does not exist
+if [[ -d "${HOME}"/.config/zsh ]]; then
+  printf "${HOME}/.config/zsh not found" >&2
   exit 129
 fi
 
-# Set ZDOTDIR
-if [[ -d "$HOME/.config/zsh" ]] \
-  && ! grep -q '^export ZDOTDIR=' /etc/zsh/zshenv; then
+# Set ZDOTDIR (we know that the zsh config directory exists at this point)
+if ! grep -q '^export ZDOTDIR=' /etc/zsh/zshenv; then
   printf '\nexport ZDOTDIR=$HOME/.config/zsh' >> /etc/zsh/zshenv
 
   # Exit if we can't set ZDOTDIR
